apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sriovdp
  name: kube-sriov-device-plugin-amd64
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sriov-device-plugin
  template:
    metadata:
      labels:
        app: sriovdp
        name: sriov-device-plugin
        tier: node
    spec:
      containers:
      - args:
        - --log-dir=sriovdp
        - --log-level=10
        image: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.5.1
        imagePullPolicy: IfNotPresent
        name: kube-sriovdp
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 40Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: devicesock
        - mountPath: /var/log
          name: log
        - mountPath: /etc/pcidp/config.json
          name: config-volume
          readOnly: true
        - mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
          name: device-info
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        sriov: enabled
      restartPolicy: Always
      serviceAccount: sriov-device-plugin
      serviceAccountName: sriov-device-plugin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/
          type: ""
        name: devicesock
      - hostPath:
          path: /var/log
          type: ""
        name: log
      - hostPath:
          path: /var/run/k8s.cni.cncf.io/devinfo/dp
          type: DirectoryOrCreate
        name: device-info
      - hostPath:
          path: /etc/pcidp/config.json
          type: ""
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate